In [284]:
import time
import numpy as np
import sklearn
import pandas as pd
import requests 
from bs4 import BeautifulSoup
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
import seaborn as sns
from pandas.plotting import scatter_matrix
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

## split to train and test:

In [285]:
cars = pd.read_csv(r'C:\Users\avoav\Introduction to Data Science\Project סמסטר א\project-semester-a\cars_data.csv' , index_col  = 'index')
cars

,version,CompanyName,year,is_GAC,is_maserati,is_daihatsu,is_porsche,is_ds,is_smart,is_seres,...,is_private,next_test_in,annual_licensing_fee,car_length,size,large,small,mini,medium,price
index,,,,,,,,,,,,,,,,,,,,,
0,קופרה פורמנטור SILVER STORM,קופרה,2021,0,0,0,0,0,0,0,...,1,5,2417,445.0,medium,0,0,0,1,176000
1,טויוטה קורולה GLI,טויוטה,2011,0,0,0,0,0,0,0,...,1,4,1262,454.5,medium,0,0,0,1,45000
2,קיה פיקנטו LX,קיה,2020,0,0,0,0,0,0,0,...,1,9,1235,359.5,mini,0,0,1,0,79900
3,הונדה סיוויק COMFORT,הונדה,2014,0,0,0,0,0,0,0,...,0,2,1424,430.0,medium,0,0,0,1,44900
4,פיאט 500 1.2 POP STAR,פיאט,2017,0,0,0,0,0,0,0,...,1,2,1353,357.1,mini,0,0,1,0,42900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2997,סקודה קודיאק AMBITION,סקודה,2017,0,0,0,0,0,0,0,...,0,5,2019,448.0,medium,0,0,0,1,132000
2998,סקודה פאביה AMBITION,סקודה,2016,0,0,0,0,0,0,0,...,0,4,1102,399.2,small,0,1,0,0,59000
2999,מאזדה 3,מאזדה,2020,0,0,0,0,0,0,0,...,1,11,2130,466.0,medium,0,0,0,1,130500
3000,קרייזלר PT-CRUISE LIMITED,קרייזלר,2008,0,0,0,0,0,0,0,...,1,3,1427,429.0,medium,0,0,0,1,17000
3001,טויוטה פריוס PLUG IN COMFORT,טויוטה,2021,0,0,0,0,0,0,0,...,1,11,2417,464.5,medium,0,0,0,1,147000

In [312]:
prices = cars['price']
Dcars = cars.copy().drop(columns = "price")

dataTrain , DataFinalTest , targetTrain  , TargetFinalTest = sklearn.model_selection.train_test_split(Dcars, prices , test_size=0.1 , random_state = 42)

In [313]:
dataTrain.to_csv(r'C:\Users\avoav\Introduction to Data Science\Project סמסטר א\project-semester-a\TrainSet_data.csv' , index_label='index' )
targetTrain.to_csv(r'C:\Users\avoav\Introduction to Data Science\Project סמסטר א\project-semester-a\TrainSet-target_data.csv' , index_label='index' )

In [314]:
DataFinalTest.to_csv(r'C:\Users\avoav\Introduction to Data Science\Project סמסטר א\project-semester-a\TestSet_data.csv' , index_label='index' )
TargetFinalTest.to_csv(r'C:\Users\avoav\Introduction to Data Science\Project סמסטר א\project-semester-a\TestSet-target_data.csv' , index_label='index' )

In [315]:
DataFinalTest = pd.read_csv(r'C:\Users\avoav\Introduction to Data Science\Project סמסטר א\project-semester-a\TestSet_data.csv' , index_col  = 'index')

DataFinalTest

,version,CompanyName,year,is_GAC,is_maserati,is_daihatsu,is_porsche,is_ds,is_smart,is_seres,...,is_company,is_private,next_test_in,annual_licensing_fee,car_length,size,large,small,mini,medium
index,,,,,,,,,,,,,,,,,,,,,
2421,מאזדה 2 ACTIVE,מאזדה,2008,0,0,0,0,0,0,0,...,0,0,9,1074,388.5,small,0,1,0,0
2891,מרצדס GLE 350D 4MATIC COUPE EXCLUS,מרצדס,2016,0,0,0,0,0,0,0,...,0,1,7,3357,399.6,small,0,1,0,0
2187,אופל אסטרה ברלינה ENJOY,אופל,2014,0,0,0,0,0,0,0,...,0,0,11,1424,465.8,medium,0,0,0,1
510,טויוטה C-HR HYBRID C-ONCEPT,טויוטה,2020,0,0,0,0,0,0,0,...,0,1,3,2130,439.0,medium,0,0,0,1
2867,איסוזו D-Max S,איסוזו,2016,0,0,0,0,0,0,0,...,0,0,11,1962,529.5,large,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2602,קיה ספורטז' URBAN,קיה,2017,0,0,0,0,0,0,0,...,0,1,11,1835,448.0,medium,0,0,0,1
240,וולבו XC40 T3 MOMENTUM,וולבו,2021,0,0,0,0,0,0,0,...,0,1,1,3366,442.5,medium,0,0,0,1
535,פיאט 500 1.2 POP,פיאט,2013,0,0,0,0,0,0,0,...,0,1,6,985,355.0,mini,0,0,1,0
703,פיג'ו 308 ACTIVE,פיג'ו,2016,0,0,0,0,0,0,0,...,0,0,3,1604,425.3,medium,0,0,0,1
2604,סקודה ראפיד AMBITION,סקודה,2018,0,0,0,0,0,0,0,...,0,0,9,1353,448.3,medium,0,0,0,1

In [316]:
TargetFinalTest

index
2421     20000
2891    344000
2187     32000
510     135900
2867    135000
         ...
2602    106500
240     199999
535      25000
703      45000
2604     56000
Name: price, Length: 298, dtype: int64

In [317]:
dataTrain =pd.read_csv(r'C:\Users\avoav\Introduction to Data Science\Project סמסטר א\project-semester-a\TrainSet_data.csv' , index_col  = 'index')
dataTrain

,version,CompanyName,year,is_GAC,is_maserati,is_daihatsu,is_porsche,is_ds,is_smart,is_seres,...,is_company,is_private,next_test_in,annual_licensing_fee,car_length,size,large,small,mini,medium
index,,,,,,,,,,,,,,,,,,,,,
1608,ב.מ.וו סדרה 3 318I BUSINESS,ב.מ.וו,2021,0,0,0,0,0,0,0,...,0,1,1,3366,470.9,large,1,0,0,0
1329,אופל מוקה X ENJOY,אופל,2017,0,0,0,0,0,0,0,...,0,1,3,1604,427.8,medium,0,0,0,1
1782,סובארו אימפרזה B3 RX,סובארו,2008,0,0,0,0,0,0,0,...,0,1,3,1074,441.5,medium,0,0,0,1
1193,יונדאי I20 INSIGHT,יונדאי,2012,0,0,0,0,0,0,0,...,0,0,8,985,399.5,small,0,1,0,0
1166,ב.מ.וו סדרה 4 420I M-SPORT,ב.מ.וו,2022,0,0,0,0,0,0,0,...,0,1,11,4731,398.6,small,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1650,מאזדה 2 PURE WHITE,מאזדה,2018,0,0,0,0,0,0,0,...,0,1,5,1353,406.0,small,0,1,0,0
1100,סקודה סופרב AMBITION,סקודה,2010,0,0,0,0,0,0,0,...,0,1,6,1427,483.8,large,1,0,0,0
1135,יונדאי טוסון SUPREME,יונדאי,2016,0,0,0,0,0,0,0,...,0,1,1,2019,447.5,medium,0,0,0,1
1300,טויוטה קורולה SUN,טויוטה,2019,0,0,0,0,0,0,0,...,0,0,7,1811,463.0,medium,0,0,0,1
865,פיג'ו 208 ACCESS,פיג'ו,2017,0,0,0,0,0,0,0,...,0,0,12,1102,397.3,small,0,1,0,0

In [318]:
targetTrain

index
1608    239000
1329     69900
1782    100000
1193     33000
1166    437320
         ...
1650     75000
1100     29000
1135    110000
1300    110000
865      41000
Name: price, Length: 2674, dtype: int64

In [319]:
#We decided that each of us would work with a model on an independent train and test
#so we would get a more accurate indication of the quality of the model

# Feature scaling

In [320]:
scaledCars = pd.read_csv(r'C:\Users\avoav\Introduction to Data Science\Project סמסטר א\project-semester-a\TrainSet_data.csv' , index_col  = 'index')
min_max_scaler = MinMaxScaler()
scaledCars[["year", "annual_licensing_fee", "engine_size",  "next_test_in" , "car_length" , "current_mileage"]] = min_max_scaler.fit_transform(scaledCars[["year", "annual_licensing_fee", "engine_size",  "next_test_in" , "car_length" ,"current_mileage"]])

In [321]:
scaledCars = scaledCars.drop(columns = ["version" , "CompanyName", "size" , "color" , "original_onership" , "engine_type" , "engine"  ] )

In [322]:
scaledCars

,year,is_GAC,is_maserati,is_daihatsu,is_porsche,is_ds,is_smart,is_seres,is_cadillac,is_דודג',...,is_leasing,is_company,is_private,next_test_in,annual_licensing_fee,car_length,large,small,mini,medium
index,,,,,,,,,,,,,,,,,,,,,
1608,0.952381,0,0,0,0,0,0,0,0,0,...,0,0,1,0.000000,0.645547,0.764326,1,0,0,0
1329,0.761905,0,0,0,0,0,0,0,0,0,...,0,0,1,0.166667,0.188003,0.600759,0,0,0,1
1782,0.333333,0,0,0,0,0,0,0,0,0,...,0,0,1,0.166667,0.050377,0.652751,0,0,0,1
1193,0.523810,0,0,0,0,0,0,0,0,0,...,1,0,0,0.583333,0.027266,0.493359,0,1,0,0
1166,1.000000,0,0,0,0,0,0,0,0,0,...,0,0,1,0.833333,1.000000,0.489943,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1650,0.809524,0,0,0,0,0,0,0,0,0,...,0,0,1,0.333333,0.122825,0.518027,0,1,0,0
1100,0.428571,0,0,0,0,0,0,0,0,0,...,0,0,1,0.416667,0.142041,0.813283,1,0,0,0
1135,0.714286,0,0,0,0,0,0,0,0,0,...,0,0,1,0.000000,0.295767,0.675522,0,0,0,1
1300,0.857143,0,0,0,0,0,0,0,0,0,...,1,0,0,0.500000,0.241755,0.734345,0,0,0,1
865,0.761905,0,0,0,0,0,0,0,0,0,...,0,0,0,0.916667,0.057647,0.485009,0,1,0,0

In [323]:
scaledCars.to_csv(r'C:\Users\avoav\Introduction to Data Science\Project סמסטר א\project-semester-a\ScaledTrainSet_data.csv' , index_label='index' )

In [324]:
scaledCars = pd.read_csv(r'C:\Users\avoav\Introduction to Data Science\Project סמסטר א\project-semester-a\ScaledTrainSet_data.csv' , index_col='index' )