In [7]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

cars = pd.read_csv(r'C:\Users\Alon\Desktop\קורסים\מדעי הנתונים\cars_data.csv')

In [8]:
#we created those models one. to import them while loading this page, use the next tab.

prices = cars['price']
Dcars = cars.copy().drop(columns = "price")

dataTrain , DataFinalTest , targetTrain  , TargetFinalTest = sklearn.model_selection.train_test_split(Dcars, prices , test_size=0.1 , random_state = 42)

In [9]:
dataTrain.to_csv(r'C:\Users\Alon\Desktop\קורסים\מדעי הנתונים\TrainSet_data.csv' , index_label='index')
targetTrain.to_csv(r'C:\Users\Alon\Desktop\קורסים\מדעי הנתונים\TrainSet-target_data.csv' , index_label='index')

In [10]:
DataFinalTest.to_csv(r'C:\Users\Alon\Desktop\קורסים\מדעי הנתונים\TestSet_data.csv' , index_label='index' )
TargetFinalTest.to_csv(r'C:\Users\Alon\Desktop\קורסים\מדעי הנתונים\TestSet-target_data.csv' , index_label='index' )

In [11]:
DataFinalTest = pd.read_csv(r'C:\Users\Alon\Desktop\קורסים\מדעי הנתונים\TestSet_data.csv' , index_col  = 'index')

DataFinalTest

,index.1,index.1.1,version,CompanyName,is_GAC,is_maserati,is_daihatsu,is_porsche,is_ds,is_smart,...,is_company,is_private,next_test_in,annual_licensing_fee,car_length,size,large,small,mini,medium
index,,,,,,,,,,,,,,,,,,,,,
2400,2421,2421,מאזדה 2 ACTIVE,מאזדה,0,0,0,0,0,0,...,0,0,9,1074,388.5,small,0,1,0,0
2862,2891,2891,מרצדס GLE 350D 4MATIC COUPE EXCLUS,מרצדס,0,0,0,0,0,0,...,0,1,7,3357,399.6,small,0,1,0,0
2167,2187,2187,אופל אסטרה ברלינה ENJOY,אופל,0,0,0,0,0,0,...,0,0,11,1424,465.8,medium,0,0,0,1
507,510,510,טויוטה C-HR HYBRID C-ONCEPT,טויוטה,0,0,0,0,0,0,...,0,1,3,2130,439.0,medium,0,0,0,1
2839,2867,2867,איסוזו D-Max S,איסוזו,0,0,0,0,0,0,...,0,0,11,1962,529.5,large,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2576,2602,2602,קיה ספורטז' URBAN,קיה,0,0,0,0,0,0,...,0,1,11,1835,448.0,medium,0,0,0,1
239,240,240,וולבו XC40 T3 MOMENTUM,וולבו,0,0,0,0,0,0,...,0,1,1,3366,442.5,medium,0,0,0,1
532,535,535,פיאט 500 1.2 POP,פיאט,0,0,0,0,0,0,...,0,1,6,985,355.0,mini,0,0,1,0
700,703,703,פיג'ו 308 ACTIVE,פיג'ו,0,0,0,0,0,0,...,0,0,3,1604,425.3,medium,0,0,0,1
2578,2604,2604,סקודה ראפיד AMBITION,סקודה,0,0,0,0,0,0,...,0,0,9,1353,448.3,medium,0,0,0,1

In [12]:
TargetFinalTest

2400     20000
2862    344000
2167     32000
507     135900
2839    135000
         ...
2576    106500
239     199999
532      25000
700      45000
2578     56000
Name: price, Length: 298, dtype: int64

In [13]:
train_set = DataFinalTest

In [15]:
demo_cars = DataFinalTest
min_max_scaler = MinMaxScaler()
demo_cars[["year", "current_mileage", "annual_licensing_fee", "engine_size",  "next_test_in" , "car_length"]] = min_max_scaler.fit_transform(demo_cars[["year", "current_mileage", "annual_licensing_fee", "engine_size",  "next_test_in" , "car_length"]])

In [16]:
demo_cars = demo_cars.drop(columns = ["version" , "CompanyName", "size" , "color" , "original_onership" , "engine_type" , "engine"  ] )

In [17]:
demo_cars.to_csv(r'C:\Users\Alon\Desktop\קורסים\מדעי הנתונים\menormal_cars_data.csv', index_label='index')

In [18]:
from sklearn.preprocessing import MinMaxScaler

In [19]:
scaledCars = pd.read_csv(r'C:\Users\Alon\Desktop\קורסים\מדעי הנתונים\TrainSet_data.csv' , index_col  = 'index')
min_max_scaler = MinMaxScaler()
scaledCars[["year", "annual_licensing_fee", "engine_size",  "next_test_in" , "car_length" , "current_mileage"]] = min_max_scaler.fit_transform(scaledCars[["year", "annual_licensing_fee", "engine_size",  "next_test_in" , "car_length" ,"current_mileage"]])

In [20]:
scaledCars = scaledCars.drop(columns = ["version" , "CompanyName", "size" , "color" , "original_onership" , "engine_type" , "engine"  ] )

In [21]:
scaledCars

,index.1,index.1.1,is_GAC,is_maserati,is_daihatsu,is_porsche,is_ds,is_smart,is_seres,is_cadillac,...,is_leasing,is_company,is_private,next_test_in,annual_licensing_fee,car_length,large,small,mini,medium
index,,,,,,,,,,,,,,,,,,,,,
1596,1608,1608,0,0,0,0,0,0,0,0,...,0,0,1,0.000000,0.645547,0.764326,1,0,0,0
1322,1329,1329,0,0,0,0,0,0,0,0,...,0,0,1,0.166667,0.188003,0.600759,0,0,0,1
1769,1782,1782,0,0,0,0,0,0,0,0,...,0,0,1,0.166667,0.050377,0.652751,0,0,0,1
1188,1193,1193,0,0,0,0,0,0,0,0,...,1,0,0,0.583333,0.027266,0.493359,0,1,0,0
1161,1166,1166,0,0,0,0,0,0,0,0,...,0,0,1,0.833333,1.000000,0.489943,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1638,1650,1650,0,0,0,0,0,0,0,0,...,0,0,1,0.333333,0.122825,0.518027,0,1,0,0
1095,1100,1100,0,0,0,0,0,0,0,0,...,0,0,1,0.416667,0.142041,0.813283,1,0,0,0
1130,1135,1135,0,0,0,0,0,0,0,0,...,0,0,1,0.000000,0.295767,0.675522,0,0,0,1
1294,1300,1300,0,0,0,0,0,0,0,0,...,1,0,0,0.500000,0.241755,0.734345,0,0,0,1
860,865,865,0,0,0,0,0,0,0,0,...,0,0,0,0.916667,0.057647,0.485009,0,1,0,0

In [60]:
scaledCars.to_csv(r'C:\Users\Alon\Desktop\קורסים\מדעי הנתונים\ScaledTrainSet_data.csv' , index_label='index' )