In [119]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
cars = pd.read_csv(r'C:\Users\Alon\Desktop\קורסים\מדעי הנתונים\cars_data.csv')

In [120]:
#we created those models one. to import them while loading this page, use the next tab.

train_set, test_set = train_test_split(cars, test_size=0.2, random_state = 40)

train_set.to_csv(r'C:\Users\Alon\Desktop\קורסים\מדעי הנתונים\train_set.csv', index_label='index')
test_set.to_csv(r'C:\Users\Alon\Desktop\קורסים\מדעי הנתונים\test_set.csv', index_label='index')
test_set = test_set.drop(columns = "engine_type")
train_set = train_set.drop(columns = "engine_type")

In [121]:
train_set = pd.read_csv(r'C:\Users\Alon\Desktop\קורסים\מדעי הנתונים\train_set.csv', index_col='index')
test_set = pd.read_csv(r'C:\Users\Alon\Desktop\קורסים\מדעי הנתונים\test_set.csv', index_col='index')

#we run 2 independent models, to check if they have the same accuracy.

In [122]:
from sklearn.preprocessing import MinMaxScaler

In [131]:
demo_cars = train_set
min_max_scaler = MinMaxScaler()
demo_cars[["year", "current_mileage", "annual_licensing_fee", "engine_size",  "next_test_in" , "car_length" , "price"]] = min_max_scaler.fit_transform(demo_cars[["year", "current_mileage", "annual_licensing_fee", "engine_size",  "next_test_in" , "car_length" , "price"]])

In [135]:
demo_cars = demo_cars.drop(columns = ["version" , "CompanyName", "size" , "color" , "original_onership" , "engine_type" , "engine"  ] )

In [137]:
demo_cars.to_csv(r'C:\Users\Alon\Desktop\קורסים\מדעי הנתונים\menormal_cars_data.csv', index_label='index')

In [139]:
demo_cars

,is_GAC,is_maserati,is_daihatsu,is_porsche,is_ds,is_smart,is_seres,is_cadillac,is_דודג',is_infinity,...,is_company,is_private,next_test_in,annual_licensing_fee,car_length,large,small,mini,medium,price
index,,,,,,,,,,,,,,,,,,,,,
2738,0,0,0,0,0,0,0,0,0,0,...,0,0,0.000000,0.027266,0.479696,0,1,0,0,0.011806
1001,0,0,0,0,0,0,0,0,0,0,...,0,1,0.333333,0.645547,0.703985,0,0,0,1,0.145833
1591,0,0,0,0,0,0,0,0,0,0,...,0,1,0.583333,0.122825,0.492220,0,1,0,0,0.041597
678,0,0,0,0,0,0,0,0,0,0,...,0,1,0.833333,1.000000,0.554839,0,1,0,0,0.222222
1223,0,0,0,0,0,0,0,0,0,0,...,0,1,0.000000,0.643210,0.749905,0,0,0,1,0.107639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1863,0,0,0,0,0,0,0,0,0,0,...,0,1,0.583333,0.280966,0.752941,0,0,0,1,0.040972
1330,0,0,0,0,0,0,0,0,0,0,...,0,0,0.250000,0.057647,0.588235,0,0,0,1,0.019028
2213,0,0,0,0,0,0,0,0,0,0,...,0,0,0.083333,0.188003,0.639469,0,0,0,1,0.033264
2055,0,0,0,0,0,0,0,0,0,0,...,0,1,0.250000,0.247988,0.742694,0,0,0,1,0.079792
2267,0,0,0,0,0,0,0,0,0,0,...,0,1,0.416667,0.219683,0.692600,0,0,0,1,0.018750